// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const procEnv = typeof process !== 'undefined' && process.env ? process.env : {} as Record<string, string | undefined>;
  const metaEnv = typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env : {} as Record<string, string | undefined>;

  const SUPABASE_URL =
    metaEnv.VITE_SUPABASE_URL ||
    procEnv.VITE_SUPABASE_URL ||
    procEnv.SUPABASE_URL ||
    metaEnv.VITE_PUBLIC_SUPABASE_URL ||
    procEnv.NEXT_PUBLIC_SUPABASE_URL ||
    '';

  const SUPABASE_KEY =
    metaEnv.VITE_SUPABASE_ANON_KEY ||
    procEnv.VITE_SUPABASE_ANON_KEY ||
    metaEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    procEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    procEnv.SUPABASE_ANON_KEY ||
    procEnv.SUPABASE_PUBLISHABLE_KEY ||
    procEnv.SUPABASE_KEY ||
    metaEnv.VITE_SUPABASE_KEY ||
    procEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
    '';

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.warn(
      '[Supabase] Supabase credentials not found in environment. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.'
    );
  }

  const validUrl = SUPABASE_URL && SUPABASE_URL.startsWith('http') ? SUPABASE_URL : 'https://placeholder.supabase.co';
  const validKey = SUPABASE_KEY || 'placeholder-anon-key';

  return createClient<Database>(validUrl, validKey, {
    global: {
      fetch: createSupabaseFetch(validKey),
    },
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
